apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-nodejs-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/lanru2001/aks-nodejs-argocd-poc.git"
    targetRevision: HEAD
    path: kubernetes
  destination:
    namespace: nodejs
    server: "https://kubernetes.default.svc" 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
     selfHeal: true
     prune: true
