apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-server-vts
  namespace: argocd
spec:
  gateways:
  - argocd-gateway
  hosts:
  - dev.argocd.com
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: dev.argocd.com
        port:
          number: 80            
