apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata: argocd-destinationroute
  name: 
spec:
  host: argo.example.com
#   subsets:
#   - name: v1
#     labels:
#       version: v1
#   - name: v2
#     labels:
#       version: v2
