# A VirtualService defines a set of traffic routing rules to apply when a host is addressed. Each routing rule defines matching criteria for traffic of a specific protocol. If the traffic is matched, then it is sent to a named destination service (or subset/version of it) defined in the registry
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd-virtualservice
  namespace: argocd
spec:
  gateways:
  - my-argocd-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: argocd-server.argocd.svc.cluster.local
        port:
          number: 80
          
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: argocd-server-vts
#   namespace: argocd
# spec:
#   gateways:
#   - argocd-gateway
#   hosts:
#   - dev1.argocdserver.com
#   http:
#     - route:
#       - destination:
#           host: argocd-server
#           port:
#             number: 80                                                                                                                                                                                         
